---
- hosts: all
  become: true
  handlers:
    - name: restart neo4j
      service: name=neo4j state=restarted
  tasks:
    - name: add neo4j key
      apt_key:
        url: "https://debian.neo4j.org/neotechnology.gpg.key"
        state: present
    - name: add neo4j repo
      apt_repository: repo='deb http://debian.neo4j.org/repo stable/' state='present'
    - name: install neo4j
      apt: name=neo4j=3.1.3
    - name: configure neo for external connections
      lineinfile:
        path: /etc/neo4j/neo4j.conf
        line: 'dbms.connectors.default_listen_address=0.0.0.0'
      notify: "restart neo4j"
    - name: symlink from import dir to openregister shared dir
      file:
        src: /mnt/openregister
        dest: /var/lib/neo4j/import/openregister
        state: link
